name: 'capstone_project'

config-version: 2
version: '0.1'

profile: 'capstone_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests", "data-tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  capstone_project:
      materialized: table
      staging:
        materialized: view